name: binderhub-badge-commenter
description: Add a BinderHub link comment on PRs
author: Simon Li
inputs:
  githubToken:
    required: true
    description: GitHub token
  query:
    required: false
    description: Optional query string to pass to the launched server, for example `urlpath=lab`
  binderUrl:
    required: true
    description: BinderHub base URL if not using mybinder.org
    default: https://mybinder.org
runs:
  using: 'node12'
  main: 'dist/index.js'
