name: mybinder-badge-commenter
description: Add a mybinder link comment on PRs
author: Simon Li
inputs:
  githubToken:
    required: true
    description: GitHub token
runs:
  using: 'node12'
  main: 'dist/index.js'
