name: test-and-update
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'

jobs:
  test-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # Ensure this matches .github/workflows/test.yml and .gitpod.Dockerfile
          node-version: '16'
          # cache: npm
      # Runs format, updates dist, runs tests
      - run: |
          npm install
          npm run all
          git diff
      - uses: stefanzweifel/git-auto-commit-action@abd87b7d94702070bef78dc1d56b6928b8fa9ecc
        with:
          commit_message: '[update-dist-bot] auto-format and update dist'
          commit_user_name: update-dist-bot
          commit_user_email: update-dist-bot@example.org
          commit_author: 'update-dist-bot <update-dist-bot@example.org>'
